apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: kube
        image: 857848422201.dkr.ecr.ap-south-1.amazonaws.com/eks:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: node-deployment-service
spec:
  type: NodePort
  ports:
  - port: 3000
  - targatePort: 3000
  - nodePort: 31900
  selector:
    app: kube
